# Generated by Django 5.0.6 on 2024-07-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mesto_back", "0002_alter_token_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="user_id",
            field=models.UUIDField(default="user_id", editable=False),
        ),
    ]
