# Generated by Django 5.0.6 on 2024-07-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mesto_back", "0005_alter_card_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
