# Generated by Django 5.0.6 on 2024-07-03 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mesto_back", "0005_alter_token_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="owner",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
