# Generated by Django 5.0.6 on 2024-07-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mesto_back", "0006_user_about_alter_user_email_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
